# Generated by Django 3.2.4 on 2021-06-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0003_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related_brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Storage.brand', verbose_name='Related Brand'),
            preserve_default=False,
        ),
    ]
