# Generated by Django 3.2.4 on 2021-06-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0004_category_related_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='related_brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
