# Generated by Django 3.2.5 on 2021-07-14 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tickets', '0001_initial'),
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTicketStatusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(max_length=350, verbose_name='Current Stage')),
                ('new_status', models.CharField(max_length=350)),
                ('created_by', models.CharField(max_length=350, verbose_name='Created By')),
                ('is_proceeded', models.BooleanField(default=False)),
                ('new_status_description', models.TextField(blank=True, null=True, verbose_name='New Status Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('proceeded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=350, verbose_name='Action')),
                ('stage', models.CharField(max_length=350, verbose_name='Stage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='Related Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Log',
                'verbose_name_plural': 'Ticket Logs',
            },
        ),
        migrations.CreateModel(
            name='SparepartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_proceeded', models.BooleanField(default=False)),
                ('proceeded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requested_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.warehouse')),
                ('requested_spareparts', models.ManyToManyField(to='Storage.SparePart')),
            ],
        ),
    ]
