# Generated by Django 3.2.4 on 2021-06-22 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clients', '0001_initial'),
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDeviceReplaceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_notes', models.TextField(verbose_name='Extra Note')),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_to_be_replaced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.clientdevice', verbose_name='Device to be replaced')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='Related Ticket')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
            options={
                'verbose_name': 'Client Device Replace Request',
                'verbose_name_plural': 'Client Devices Replace Requests',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=350, verbose_name='App Name')),
                ('action_type', models.CharField(max_length=350, verbose_name='Action Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_note', models.TextField(verbose_name='Extra Note')),
                ('storage_approved', models.BooleanField(default=False, verbose_name='Storage Approved')),
                ('supervisor_approved', models.BooleanField(default=False, verbose_name='Supervisor Approved')),
                ('spare_parts_availability_date', models.DateField(blank=True, null=True, verbose_name='Spare Part Availability Date')),
                ('admin_approved', models.BooleanField(default=False, verbose_name='Admin Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_ticket_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticketdevice', verbose_name='Related ticket device ')),
                ('required_spare_parts', models.ManyToManyField(to='Storage.SparePart', verbose_name='Required Spare Part')),
            ],
            options={
                'verbose_name': 'Spare Part Request',
                'verbose_name_plural': 'Spare Parts Requests',
            },
        ),
        migrations.CreateModel(
            name='SparePartsRequestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=350, verbose_name='Action Type')),
                ('storage_approved', models.BooleanField(default=False, verbose_name='Storage Approved')),
                ('supervisor_approved', models.BooleanField(default=False, verbose_name='Supervisor Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_request', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='System_Updates.sparepartsrequest', verbose_name='Related Request')),
            ],
            options={
                'verbose_name': 'Spare Parts Request Update',
                'verbose_name_plural': 'Spare Parts Request Updates',
            },
        ),
        migrations.CreateModel(
            name='CustodyReleaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_proceeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_ticket', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='Related Ticket')),
                ('released_custody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.item', verbose_name='Released Custody')),
                ('released_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Released To')),
                ('requested_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.warehouse', verbose_name='Requested From')),
            ],
            options={
                'verbose_name': 'Custody Release Request',
                'verbose_name_plural': 'Custody Release Requests',
            },
        ),
        migrations.CreateModel(
            name='ClientDeviceReplaceRequestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Updates.clientdevicereplacerequest', verbose_name='Related request')),
            ],
            options={
                'verbose_name': 'Client Device Replace Request Update',
                'verbose_name_plural': 'Client Device Replace Request Updates',
            },
        ),
        migrations.CreateModel(
            name='ChangeTicketStatusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_status', models.CharField(max_length=350, verbose_name='Requested Status')),
                ('request_proceeded', models.BooleanField(default=False, verbose_name='Request Proceeded')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='Related Ticket')),
            ],
            options={
                'verbose_name': 'Change Ticket Status Request',
                'verbose_name_plural': 'Change Ticket Status Requests',
            },
        ),
        migrations.CreateModel(
            name='CallbackReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_text', models.TextField(verbose_name='Reminder Text')),
                ('remind_at', models.DateTimeField(verbose_name='Remind at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_ticket', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='Related Ticket')),
                ('user_to_be_reminded', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User to be reminded')),
            ],
            options={
                'verbose_name': 'Callback Reminder',
                'verbose_name_plural': 'Callback Reminders',
            },
        ),
    ]
