# Generated by Django 3.2.5 on 2021-07-11 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tickets', '0001_initial'),
        ('Storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTicketStatusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_status', models.CharField(max_length=350)),
                ('is_proceeded', models.BooleanField(default=False)),
                ('proceeded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='SparepartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_proceeded', models.BooleanField(default=False)),
                ('proceeded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requested_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.warehouse')),
                ('requested_spareparts', models.ManyToManyField(to='Storage.SparePart')),
            ],
        ),
    ]
