# Generated by Django 3.2.5 on 2021-07-11 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('System_Updates', '0003_alter_updateticketstatusrequest_proceeded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateticketstatusrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 11, 21, 1, 5, 531191, tzinfo=utc), verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
