# Generated by Django 3.2.5 on 2021-09-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Updates', '0003_clientlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='created_by',
            field=models.CharField(max_length=350, verbose_name='Created by'),
        ),
    ]
