# Generated by Django 3.2.5 on 2021-09-14 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System_Updates', '0004_alter_ticketlog_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
