# Generated by Django 3.2.4 on 2021-06-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(max_length=750, verbose_name='Client Full Name')),
                ('client_phone_number_1', models.CharField(max_length=750, verbose_name='Client Phone Number 1')),
                ('client_phone_number_2', models.CharField(max_length=750, verbose_name='Client Phone Number 2')),
                ('client_landline_number', models.CharField(max_length=750, verbose_name='Client Landline Number')),
                ('client_city', models.CharField(max_length=350, verbose_name='Client City')),
                ('client_region', models.CharField(max_length=350, verbose_name='Client Region')),
                ('client_address_1', models.CharField(max_length=750, verbose_name='Client Address 1')),
                ('client_address_2', models.CharField(max_length=750, verbose_name='Client Address 2')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_feeding_source', models.CharField(max_length=350, verbose_name='Device Feeding Source')),
                ('purchase_date', models.DateField(null=True, verbose_name='Purchase Date')),
                ('installation_date', models.DateField(null=True, verbose_name='Installation Date')),
                ('warranty_starting_date', models.DateField(null=True, verbose_name='Warranty Starting Date')),
                ('installed_through_the_company', models.BooleanField(default=False, verbose_name='Installed Through The Company')),
                ('in_warranty', models.BooleanField(default=False, verbose_name='In Warranty')),
                ('related_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.client', verbose_name='Related Client')),
                ('related_storage_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.item', verbose_name='Related Storage Item')),
            ],
            options={
                'verbose_name': 'Client Device',
                'verbose_name_plural': 'Client Devices',
            },
        ),
    ]
