# Generated by Django 3.2.5 on 2021-07-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdevice',
            name='installation_visit_date',
        ),
        migrations.RemoveField(
            model_name='clientdevice',
            name='related_brand',
        ),
        migrations.RemoveField(
            model_name='clientdevice',
            name='related_category',
        ),
    ]
