# Generated by Django 3.2.5 on 2021-07-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_address_1',
            new_name='client_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_address_2',
        ),
        migrations.AddField(
            model_name='client',
            name='client_address_landmark',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Client Address Landmark'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_apartment_no',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Client Apartment No'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_building_no',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Client Building No'),
        ),
    ]
