# Generated by Django 3.2.4 on 2021-06-30 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0005_auto_20210628_1419'),
        ('Configurations', '0001_initial'),
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdevice',
            name='in_warranty',
        ),
        migrations.RemoveField(
            model_name='clientdevice',
            name='installed_through_the_company',
        ),
        migrations.RemoveField(
            model_name='clientdevice',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='clientdevice',
            name='warranty_starting_date',
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='device_invoice',
            field=models.FileField(default='device_invoice.pdf', upload_to='Client_Devices_Invoices', verbose_name='Device Invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='purchasing_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Purchasing Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='related_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Configurations.brand', verbose_name='Related Brand'),
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='related_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Configurations.category', verbose_name='Related Category'),
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='warranty_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Warranty Start Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='installation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Installation Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='related_storage_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Storage.item', verbose_name='Related Storage Item'),
        ),
    ]
