# Generated by Django 3.2.5 on 2021-07-14 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_auto_20210714_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='expected_warranty_start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 21, 16, 46, 761205, tzinfo=utc), verbose_name='Warranty Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Manufacturing Date'),
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installation Date'),
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='purchasing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchasing Date'),
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty Start Date'),
        ),
    ]
