# Generated by Django 3.2.4 on 2021-06-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_auto_20210630_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='in_warranty',
            field=models.BooleanField(default=True, verbose_name='In Warranty'),
        ),
    ]
