# Generated by Django 3.2.4 on 2021-07-01 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_clientdevice_in_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='installation_visit_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Installation Visit Date'),
            preserve_default=False,
        ),
    ]
