# Generated by Django 3.2.5 on 2021-07-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_auto_20210714_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdevice',
            name='in_warranty',
            field=models.BooleanField(blank=True, null=True, verbose_name='In Warranty'),
        ),
    ]
