# Generated by Django 3.2.5 on 2021-07-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_alter_clientdevice_in_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdevice',
            name='expected_warranty_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty Start Date'),
        ),
    ]
