# Generated by Django 3.2.4 on 2021-07-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0001_initial'),
        ('Clients', '0004_clientdevice_installation_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='related_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Configurations.branch', verbose_name='Related Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='related_distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Configurations.distributor', verbose_name='Related Distributor'),
            preserve_default=False,
        ),
    ]
