# Generated by Django 3.2.5 on 2021-07-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_alter_clientdevice_expected_warranty_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdevice',
            name='related_branch',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Related Branch'),
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='related_distributor',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Related Distributor'),
        ),
    ]
