# Generated by Django 3.2.5 on 2021-07-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_auto_20210715_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='is_installed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Installed'),
        ),
    ]
