# Generated by Django 3.2.5 on 2021-07-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_clientdevice_is_installed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdevice',
            old_name='is_installed',
            new_name='installed_through_the_company',
        ),
    ]
