# Generated by Django 3.2.5 on 2021-07-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0009_auto_20210715_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdevice',
            old_name='device_invoice_or_manufacturer',
            new_name='device_invoice_or_manufacturer_label',
        ),
    ]
