# Generated by Django 3.2.5 on 2021-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0012_alter_clientdevice_installed_through_the_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_floor_no',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Client Floor No'),
        ),
    ]
