# Generated by Django 3.2.5 on 2021-09-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0013_client_client_floor_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdevice',
            name='installed_through_the_company',
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='installation_status',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Installation status'),
        ),
    ]
