# Generated by Django 3.2.5 on 2021-09-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0014_auto_20210906_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
    ]
