# Generated by Django 3.2.4 on 2021-06-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=350, verbose_name='Branch Name')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=350, verbose_name='Brand Name')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_name', models.CharField(max_length=350, verbose_name='distributor_name')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('hoods', 'Hoods'), ('slim-hobs', 'Slim Hobs'), ('ovens', 'Ovens'), ('cookers', 'Cookers')], max_length=350, verbose_name='Category Name')),
                ('category_feeding_source', models.CharField(choices=[('natural-gas', 'Natural Gas'), ('gas-cylinder', 'Gas Cylinder'), ('internal-expulsion', 'Internal Expulsion'), ('external-expulsion', 'External Expulsion')], max_length=350, verbose_name='Category Feeding Source')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('related_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configurations.brand', verbose_name='Related Brand')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
