# Generated by Django 3.2.5 on 2021-08-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='related_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Configurations.city', verbose_name='Related City'),
        ),
    ]
