# Generated by Django 3.2.5 on 2021-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0002_region_related_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_feeding_source',
            field=models.CharField(choices=[('natural-gas', 'Natural Gas'), ('gas-cylinder', 'Gas Cylinder'), ('electricity', 'Electricty'), ('internal-expulsion', 'Internal Expulsion'), ('external-expulsion', 'External Expulsion')], max_length=350, verbose_name='Category Feeding Source'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('hoods', 'Hoods'), ('slim-hobs', 'Slim Hobs'), ('gas-ovens', 'Gas Ovens'), ('electric-ovens', 'Electric Ovens'), ('cookers', 'Cookers')], max_length=350, verbose_name='Category Name'),
        ),
    ]
