# Generated by Django 3.2.4 on 2021-07-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0002_ticketstatus_tickettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDiagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=350, verbose_name='Issue Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('related_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configurations.category', verbose_name='Related Category')),
            ],
            options={
                'verbose_name': 'Common Diagnostic',
                'verbose_name_plural': 'Common Diagnostics',
            },
        ),
    ]
