# Generated by Django 3.2.5 on 2021-09-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0003_auto_20210811_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('hood', 'Hood'), ('slim-hob', 'Slim Hob'), ('gas-oven', 'Gas Oven'), ('electric-oven', 'Electric Oven'), ('cooker', 'Cooker')], max_length=350, verbose_name='Category Name'),
        ),
    ]
