# Generated by Django 3.2.5 on 2021-07-14 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Configurations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Storage', '0001_initial'),
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(max_length=350, verbose_name='Current Stage')),
                ('closed_by', models.CharField(blank=True, max_length=350, null=True, verbose_name='Closed By')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is Closed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.client', verbose_name='Related Client')),
                ('related_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related Technician')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ticket_type', models.CharField(max_length=350, verbose_name='Device Ticket type')),
                ('common_diagnostics', models.CharField(blank=True, max_length=350, null=True, verbose_name='Common Diagnostics')),
                ('is_completed', models.BooleanField(blank=True, null=True, verbose_name='Is Completed')),
                ('is_not_completed', models.BooleanField(blank=True, null=True, verbose_name='Is Not Completed')),
                ('not_completed_notes', models.TextField(blank=True, null=True, verbose_name='Not Completed Notes')),
                ('extra_notes', models.TextField(blank=True, default='Device Extra Notes Goes Here', null=True, verbose_name='Extra Notes')),
                ('related_client_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.clientdevice', verbose_name='Related Client Device')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='Related Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Device',
                'verbose_name_plural': 'Ticket Devices',
            },
        ),
        migrations.CreateModel(
            name='TicketFollowbackCallRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='Related Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Followback Call Rating',
                'verbose_name_plural': 'Ticket Followback Call Ratings',
            },
        ),
        migrations.CreateModel(
            name='TicketDeviceSpareparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.IntegerField(verbose_name='Required QTY')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('assigned_sparepart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Storage.sparepart', verbose_name='Assigned Spareparts')),
                ('related_ticket_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticketdevice', verbose_name='Related Ticket Device')),
            ],
            options={
                'verbose_name': 'Ticket Device Spareparts',
                'verbose_name_plural': 'Tickets Devices Spareparts',
            },
        ),
        migrations.CreateModel(
            name='TicketDeviceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.IntegerField(verbose_name='Required QTY')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('assigned_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Configurations.ticketservice', verbose_name='Assigned Service')),
                ('related_ticket_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticketdevice', verbose_name='Related Ticket Device')),
            ],
            options={
                'verbose_name': 'Ticket Device Service',
                'verbose_name_plural': 'Tickets Devices Services',
            },
        ),
    ]
