# Generated by Django 3.2.5 on 2021-07-11 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Storage', '0001_initial'),
        ('Clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.client', verbose_name='Related Client')),
                ('related_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related Technician')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_ticket_status', models.CharField(max_length=350, verbose_name='New Ticket Status')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('currently_assigned_technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Currently Assigned Technician')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='Related Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Update',
                'verbose_name_plural': 'Ticket Updates',
            },
        ),
        migrations.CreateModel(
            name='TicketDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ticket_type', models.CharField(max_length=350, verbose_name='Device Ticket type')),
                ('device_ticket_status', models.CharField(max_length=350, verbose_name='Device Ticket Status')),
                ('common_diagnostics', models.CharField(blank=True, max_length=350, null=True, verbose_name='Common Diagnostics')),
                ('extra_notes', models.TextField(blank=True, default='Device Extra Notes Goes Here', null=True, verbose_name='Extra Notes')),
                ('assigned_spareparts', models.ManyToManyField(to='Storage.SparePart', verbose_name='Assigned Spareparts')),
                ('related_client_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.clientdevice', verbose_name='Related Client Device')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='Related Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Device',
                'verbose_name_plural': 'Ticket Devices',
            },
        ),
    ]
