# Generated by Django 3.2.5 on 2021-07-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Cost'),
        ),
    ]
