# Generated by Django 3.2.5 on 2021-07-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdevice',
            name='assigned_spareparts',
        ),
        migrations.CreateModel(
            name='TicketDeviceSpareparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('assigned_spareparts', models.ManyToManyField(to='Storage.SparePart', verbose_name='Assigned Spareparts')),
                ('related_ticket_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticketdevice', verbose_name='Related Ticket Device')),
            ],
            options={
                'verbose_name': 'Ticket Device Spareparts',
                'verbose_name_plural': 'Tickets Devices Spareparts',
            },
        ),
    ]
