# Generated by Django 3.2.4 on 2021-07-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
    ]
