# Generated by Django 3.2.5 on 2021-07-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_ticket_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total_cost',
            field=models.FloatField(default=0.0, verbose_name='Total Cost'),
        ),
    ]
