# Generated by Django 3.2.4 on 2021-07-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_auto_20210702_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdevice',
            name='device_service_type',
        ),
        migrations.AddField(
            model_name='ticketdevice',
            name='device_ticket_status',
            field=models.CharField(default='pre-intialized', max_length=350, verbose_name='Device Ticket Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketdevice',
            name='device_ticket_type',
            field=models.CharField(default='pre-intialized', max_length=350, verbose_name='Device Ticket type'),
            preserve_default=False,
        ),
    ]
