# Generated by Django 3.2.4 on 2021-07-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_auto_20210702_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdevice',
            name='device_extra_service_type',
        ),
        migrations.AddField(
            model_name='ticketdevice',
            name='extra_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Extra Notes'),
        ),
    ]
