# Generated by Django 3.2.4 on 2021-07-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_auto_20210702_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdevice',
            name='extra_notes',
            field=models.TextField(blank=True, default='Device Extra Notes Goes Here', null=True, verbose_name='Extra Notes'),
        ),
    ]
