# Generated by Django 3.2.5 on 2021-08-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_cookerinstallationrequirementsform_electricoveninstallationrequirementsform_gasoveninstallationrequi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookerinstallationrequirementsform',
            name='related_ticket_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticketdevice', verbose_name='Related Ticket Device'),
        ),
        migrations.AddField(
            model_name='electricoveninstallationrequirementsform',
            name='related_ticket_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticketdevice', verbose_name='Related Ticket Device'),
        ),
        migrations.AddField(
            model_name='gasoveninstallationrequirementsform',
            name='related_ticket_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticketdevice', verbose_name='Related Ticket Device'),
        ),
        migrations.AddField(
            model_name='hoodinstallationrequirementsform',
            name='related_ticket_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticketdevice', verbose_name='Related Ticket Device'),
        ),
        migrations.AddField(
            model_name='slimhobinstallationrequirementsform',
            name='related_ticket_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticketdevice', verbose_name='Related Ticket Device'),
        ),
    ]
