# Generated by Django 3.2.4 on 2021-07-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0005_alter_ticketdevice_extra_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdevice',
            name='common_diagnostics',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Common Diagnostics'),
        ),
    ]
