# Generated by Django 3.2.5 on 2021-08-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0005_auto_20210807_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoodinstallationrequirementsform',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket'),
        ),
    ]
