# Generated by Django 3.2.5 on 2021-08-07 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0007_cookerinstallationrequirementsform_related_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slimhobinstallationrequirementsform',
            name='marble_dropping_hole_is_available',
        ),
        migrations.RemoveField(
            model_name='slimhobinstallationrequirementsform',
            name='marble_dropping_hole_measurements',
        ),
        migrations.AddField(
            model_name='slimhobinstallationrequirementsform',
            name='marble_opening_hole_is_available',
            field=models.BooleanField(default=True, verbose_name='Marble Opening Hole'),
        ),
        migrations.AddField(
            model_name='slimhobinstallationrequirementsform',
            name='marble_opening_hole_measurements',
            field=models.CharField(default='21', max_length=350, verbose_name='Marble Opening Hole Measurements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slimhobinstallationrequirementsform',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket'),
        ),
    ]
