# Generated by Django 3.2.5 on 2021-08-08 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0008_auto_20210808_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricoveninstallationrequirementsform',
            old_name='ventillation_hole_is_available',
            new_name='ventillation_opening_is_available',
        ),
        migrations.RenameField(
            model_name='electricoveninstallationrequirementsform',
            old_name='ventillation_hole_measurements',
            new_name='ventillation_opening_measurements',
        ),
        migrations.AddField(
            model_name='electricoveninstallationrequirementsform',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket'),
        ),
    ]
