# Generated by Django 3.2.5 on 2021-08-08 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0009_auto_20210808_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasoveninstallationrequirementsform',
            name='ventillation_hole_below_oven_is_available',
        ),
        migrations.RemoveField(
            model_name='gasoveninstallationrequirementsform',
            name='ventillation_hole_below_oven_measurements',
        ),
        migrations.RemoveField(
            model_name='gasoveninstallationrequirementsform',
            name='ventillation_hole_in_front_of_oven_is_available',
        ),
        migrations.RemoveField(
            model_name='gasoveninstallationrequirementsform',
            name='ventillation_hole_in_front_of_oven_measurements',
        ),
        migrations.AddField(
            model_name='gasoveninstallationrequirementsform',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket'),
        ),
        migrations.AddField(
            model_name='gasoveninstallationrequirementsform',
            name='ventillation_opening_below_oven_is_available',
            field=models.BooleanField(default=True, verbose_name='Ventaillation Opening Below Oven Is Available'),
        ),
        migrations.AddField(
            model_name='gasoveninstallationrequirementsform',
            name='ventillation_opening_below_oven_measurements',
            field=models.CharField(default='21', max_length=350, verbose_name='Ventillation Opening Below Oven Measurements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasoveninstallationrequirementsform',
            name='ventillation_opening_in_front_of_oven_is_available',
            field=models.BooleanField(default=True, verbose_name='Ventaillaiton Opening In Front Of Oven Is Available'),
        ),
        migrations.AddField(
            model_name='gasoveninstallationrequirementsform',
            name='ventillation_opening_in_front_of_oven_measurements',
            field=models.CharField(default='12', max_length=350, verbose_name='Ventaillaiton Opening In Front Of Oven Measurements'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electricoveninstallationrequirementsform',
            name='ventillation_opening_is_available',
            field=models.BooleanField(default=True, verbose_name='Ventillation Opening Is Available'),
        ),
        migrations.AlterField(
            model_name='electricoveninstallationrequirementsform',
            name='ventillation_opening_measurements',
            field=models.CharField(max_length=350, verbose_name='Ventillation Opening Measurements'),
        ),
    ]
