# Generated by Django 3.2.5 on 2021-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0011_gasoveninstallationrequirementsform_gas_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdevice',
            name='customer_service_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Service Notes'),
        ),
    ]
