# Generated by Django 3.2.5 on 2021-08-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0013_ticketdevice_re_opened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdevice',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='ticketdevice',
            name='is_not_completed',
        ),
        migrations.RemoveField(
            model_name='ticketdevice',
            name='re_opened',
        ),
        migrations.AddField(
            model_name='ticketdevice',
            name='device_ticket_status',
            field=models.CharField(default='Under Processing', max_length=350, verbose_name='Device Ticket Status'),
        ),
    ]
