# Generated by Django 3.2.5 on 2021-08-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0014_auto_20210812_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdevice',
            name='extra_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Extra Notes'),
        ),
    ]
