# Generated by Django 3.2.5 on 2021-09-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0016_ticket_ticket_generated_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdevice',
            name='reminder_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Reminder notes'),
        ),
    ]
