# Generated by Django 3.2.5 on 2021-09-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0017_ticketdevice_reminder_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdevice',
            name='customer_service_notes',
        ),
        migrations.RemoveField(
            model_name='ticketdevice',
            name='reminder_notes',
        ),
        migrations.AddField(
            model_name='ticketdevice',
            name='technical_support_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Technical support notes'),
        ),
        migrations.AddField(
            model_name='ticketdevice',
            name='technicans_supervisor_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Technicians supervisor notes'),
        ),
    ]
