# Generated by Django 3.2.5 on 2021-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0018_auto_20210916_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdevice',
            name='agent_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Agent notes'),
        ),
    ]
