# Generated by Django 3.2.5 on 2021-09-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0019_ticketdevice_agent_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdevice',
            name='redirection_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Redirection notes'),
        ),
    ]
