# Generated by Django 3.2.5 on 2021-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0020_ticketdevice_redirection_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Ticket status'),
        ),
    ]
