# Generated by Django 3.2.5 on 2021-09-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0021_auto_20210917_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_forced_status',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Ticket forced status'),
        ),
    ]
