# Generated by Django 3.2.5 on 2021-09-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configurations', '0005_route'),
        ('Tickets', '0025_auto_20210920_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='related_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Configurations.route', verbose_name='Related route'),
        ),
    ]
